# Generated by Django 5.0.7 on 2024-11-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
    ]
