# Generated by Django 5.0.7 on 2024-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('airline', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=3)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=5)),
            ],
        ),
    ]
